### ISSUE TITLE
Compatible desktop - syncservice versions

### ISSUE THREAD

**Issue by ashish-kale** [stacksync/desktop#12]
I am using package “stacksync-server_0.6.10_all.deb” for server and “StackSync_2.0_all.exe” for client.
Still getting issues similar to -> https://github.com/stacksync/desktop/issues/9

This issue(https://github.com/stacksync/desktop/issues/8) states that my versions are correct.

Can I please get a list of compatible client and server versions as I also want to upgrade to the latest version?

**Comment by Cotes** [comment]
Hi @ashish-kale ,

Here you have a list of compatible versions (from newest to oldest):
Desktop client - StackSync server
v2.0.1 - 0.6.13
v2.0-alpha3 - 0.6.11
v2.0-alpha2 - 0.5.1
v2.0-alpha1 - 0.5.0

Best,
Cristian.

**Comment by ashish-kale** [comment]
Thanks for the reply! I will try and update the results.

**Comment by ashish-kale** [comment]
I am using 
Desktop client - StackSync server
v2.0.1 - 0.6.13

Getting this error on the client:-

java.lang.Exception: PYTHON SCRIPT ERROR:
FATAL EXCEPTION: <class 'socket.error'>
	at com.stacksync.desktop.gui.linux.LinuxNativeClient.startService(LinuxNativeClient.java:317)
	at com.stacksync.desktop.gui.linux.LinuxNativeClient.init(LinuxNativeClient.java:86)
	at com.stacksync.desktop.gui.tray.platform.LinuxTray.init(LinuxTray.java:50)
	at com.stacksync.desktop.Application.initUI(Application.java:214)
	at com.stacksync.desktop.Application.start(Application.java:120)
	at com.stacksync.desktop.Stacksync.start(Stacksync.java:144)
	at com.stacksync.desktop.Stacksync.main(Stacksync.java:197)

Can you help in resolving this?

**Comment by Cotes** [comment]
It seems that there is an error when the client tries to execute the native.py python script. Concretely I think that the problem is related with the python-notify library.

Try this:
sudo apt-get install python-notify

And relaunch the client.
