### ISSUE TITLE
New files not syncing without restart

### ISSUE THREAD

**Issue by ashish-kale** [stacksync/desktop#13]
We are getting this error when the client is adding a new file:-

[2015-08-21 11:55:59] INFO Thread-9 RemoteWorkspaceImpl.notifyCommit:78 - Error parsing: com.stacksync.commons.models.CommitInfo@41042a3
java.lang.NullPointerException
	at com.stacksync.desktop.syncserver.RemoteWorkspaceImpl.doActionCommitted(RemoteWorkspaceImpl.java:95)
	at com.stacksync.desktop.syncserver.RemoteWorkspaceImpl.notifyCommit(RemoteWorkspaceImpl.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at omq.server.RemoteObject.invokeMethod(RemoteObject.java:169)
	at omq.server.InvocationThread.run(InvocationThread.java:56)

Due to this change is not synced to other clients. When the new client is restarted, the changes are synced

**Comment by ashish-kale** [comment]
This issue is occurring when one client is installed on Windows and the other on Linux(Linux mint)

**Comment by ashish-kale** [comment]
Server version 0.6.13
Client version 2.0.1

**Comment by Cotes** [comment]
Hi ashish-kale,

I don't think that this problem is related with the OS that you are using to sync files and the versions that you are using are correct :)

It seems that there is a problem with some file metadata. To have a better understanding about the problem, I would need to take a look at the server database. Maybe there I find the error and why it is produced.

Cristian.
